on:
    workflow_dispatch:
    push:
jobs:
    notify-wip-commit:
        name: Run this job if commit message contains wip
        if: contains(github.event.head_commit.message, 'wip')
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "The lastest commit is wip"
    notify-non-wip-commit:
        name: Run this job if commit message does not contain wip
        if: !contains(github.event.head_commit.message, 'wip')
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "The lastest commit is not wip"

  