on:
    workflow_dispatch:


jobs:
    introduce-nested-wf:
        runs-on: ubuntu-latest
        steps:
            - name: Introduce nested-workflow
              run: echo "This demonstrates how to call nested workflows"

    workflow-b:
        uses: ./.github/workflows/workflow-b.yml

    workflow-c:
        uses: ./.github/workflows/workflow-c.yml