on:
    workflow_call:


jobs:
    introduce-wf-b:
        runs-on: ubuntu-latest
        steps:
            - name: Introduce workflow B
              run: echo "This is workflow B"

    workflow-c:
        uses: ./.github/workflows/workflow-c.yml